- name: 'OS_USERNAME'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'user'

- name: 'OS_PASSWORD'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'password'

- name: 'OS_DOMAIN_NAME'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'domain_name'

- name: 'OS_AUTH_URL'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'auth_url'

- name: 'OS_REGION_NAME'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'region_name'

- name: 'OS_PROJECT_ID'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'project_id'

- name: 'OS_PROJECT_NAME'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'project_name'

- name: 'OS_PROJECT_DOMAIN_ID'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'os_project_domain_id'

- name: 'OS_INTERFACE'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'os_interface'

- name: 'OS_IDENTITY_API'
  valueFrom:
    secretKeyRef:
      name: 'jenkins-openstack-credentials'
      key: 'os_identity_api_version'
